config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :answer_ratings
  resources :questions do
    resources :answers
  end
  resources :users
  resources :topics, only: [:index, :show, :destroy]
  resources :categories, only: [:index, :show]
  resources :posts, only: [:destroy]
  resources :answers, only: [:destroy]
  resources :comments, only: [:destroy]

  post 'set_new_question_category', to: "application#set_new_question_category", as: :set_new_question_category
  post 'create_new_question', to: "application#create_new_question", as: :create_new_question
  match "home" => "home#index", as: :home_index, via: [:get, :post]
  post "create_post", to: "home#create_post", as: :create_post
  post "categories/create_topic", to: "categories#create_topic", as: :create_topic


  get 'set_topic_options', to: "application#set_topic_options", as: :set_topic_options
  match "/categories/topics/questions" => "questions#byTopic" , :via => [:get]
  post "questions/create_comment", to: "questions#create_comment",  as: :create_comment

  patch "topics/approve/:id", to: "topics#approve", as: 'approve_topics'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
  scope :by_date, -> { order(created_at: :desc) }

  validates :question_title, :question_text, :topic_id, :user_id, presence: true 
end

app/controllers/questions_controller.rb
# Questions controller
class QuestionsController < ApplicationController
  before_action :set_search

  def set_search
    @q1=Question.search(params[:q])
    @questions = Question.all
  end
  
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
    @question.answers.build
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_path
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to question_path(@comment.answer.question_id)
  end

  def edit
    @question = Question.find(params[:id])
    @question.answers.build
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to question_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to home_index_path
  end

  private

  def question_params
    params.require(:question).permit(:id, :question_title, :question_text, answers_attributes: [ :id, :answer_text, :question_id, :_destroy])
  end

  def comment_params
    params.require(:comment).permit(:comment_text, :answer_id, :user_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  <div class="TabbedPanelsContent">
    <%= f.text_area :answer_text, class: "form-control mr-sm-2 form-answer-text", cols: "100", rows:"3", placeholder: "Write your answer here", style:"resize: none;" %>
  </div>
  <%= link_to 'Cancel', "#", id:"cancel-write-answer", class: "btn btn-outline-secondary", style:"margin-top:0.5rem;" %>
  <%= f.submit "Submit answer", class: "btn btn-success", style:"margin-top:0.5rem;" %>
<% end %>

app/views/questions/_formComment.html.erb
<%= form_for([answer, answer.comments.build], url: "create_comment", html: {id:"form-comment-#{answer.id}"}) do |f| %>
    <div class="media comment-container">
        <%= image_tag( current_user.avatar.url, class:"align-self-top mr-3 media-object comment", alt: current_user.avatar.url )%>
        <div class="media-body">
            <div class="comment-text-button">
                <div type="text" id="textarea-comment-<%=answer.id%>" class="lead textarea-new-comment" autofocus contenteditable></div>
                <div class="button-comment-container">
                    <%=link_to 'Cancel', "#", id:"cancel-comment-#{answer.id}", class: "cancel-write-comment", style:"margin-top:0.5rem;" %>
                </div>
            </div>
        </div>
    </div>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= f.hidden_field :comment_text, id: "answer-comment-#{answer.id}"%>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :answer_id, value: answer.id %>
<% end %>

app/views/questions/_new.html.erb
<div id="new-question-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content" id="ask-question-content">
       <div class="modal-header modal-header-no-line">
          <h5 id="new-question-modal-title-1" class="modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="new-question-modal-body-footer"></div>
    </div>
  </div>
</div>

<div id="new-question-first-body" class="new-question-body">
  <div id="new-question-first-body-content">
    <div class="modal-body modal-body-no-top-padding">
      <div class="container-fluid">
        <%= form_tag set_new_question_category_path do %>
          <div class="row bg-white">
            <% @categories.each do |category| %>
              <div class="col-sm-6 col-category">
                <label class="card card-category mb-3">
                  <%= radio_button_tag 'category_name', category.category_name, true, class: "category_input", :onclick => "this.form.submit();" %>
                  <%= image_tag("categories/" + category.id.to_s+ ".jpeg", class: "card-img-top imgCategory", alt: "category.category_name")%>
                  <div class="centered lead"><%= category.category_name %></div>
                </label>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="new-question-second-body" class="new-question-body">
  <div id="new-question-second-body-content">
    <h5 id="new-question-modal-title" class="modal-title"></h5>
    <%= form_tag create_new_question_path, :id => 'create-new-question-form' do %>
      <div class="modal-body modal-body-no-top-padding">
        <div class="input-group mb-3 new-question-topic">
          <%= text_field_tag 'topic_name', nil, class: 'form-control', required: 'true', data: { autocomplete_source: set_topic_options_path } %>
        </div>
        <div class="input-group mb-3 new-question-question">
          <%= text_field_tag 'question_title', nil, class: 'form-control', required: 'true', minlength: "20", placeholder: "Type your question here" %>
        </div>
        <div class="input-group mb-3 new-question-question">
          <%= text_area_tag 'question_text', nil, class: 'form-control', rows: 6, required: 'true', placeholder: "Write a description about your question here" %>
        </div>
      </div>
      <div class="modal-footer new-question-topic">
        <button type="button" class="btn btn-warning btn-back">Back</button>
        <button type="button" class="btn btn-primary btn-continue">Continue</button>
      </div>
      <div class="modal-footer new-question-question">
        <button type="button" class="btn btn-warning btn-back">Back</button>
        <%= submit_tag "Post", class: "btn btn-success btn-continue" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/_questions.html.erb
<div class="questionContent">
  <% @questions.by_date.each do |question| %>
    <div class="question-information">
      <div class="question-info">
        <div class="answer-quantity">
          <%= question.answers.count %>
        </div>
        <div>
          <%= "answer".pluralize(question.answers.count) %>
        </div>
      </div>
      <div>
        <div class="questionTitle">
          <%= link_to question.question_title, question_path(question), class: "link-to-question"%>
        </div>
        <p class="questionText">
          <%= question.question_text %>
        </p>
        <small class="user-info">
          <%= question_timestamp(question) %>
        </small>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/questions/index.html.erb
<%= render "questions" %>

app/views/questions/show.html.erb
<div class="container">
    <div class="container">
        <div class="jumbotron bannerHeader" id="questionHeader">
            <div class="delete-time-container">
                <% if current_user.admin == true %>
                  <%= link_to ('<i class="fas fa-minus-circle delete-item" style="font-size:1.5em"></i>').html_safe, question_path(@question), method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
                <span class="user-info long-text lead">
                    <%= question_show_timestamp(@question) %> 
                </span>
            </div>
            <span class="badge badge-pill badge-secondary"><%= @question.topic.category.category_name %></span>
            <span class="badge badge-pill badge-secondary"><%= @question.topic.topic_name %></span>
            <h1 class="display-4"><%= @question.question_title %></h1>
            <p class="long-text lead">
                <%= @question.question_text %>
            </p>
            <span class="badge badge-pill badge-secondary" id="answer-counter"><%= @question.answers.count %> Answers</span>
        </div>  

        <% if @question.answers.count <= 0 %>
          <hr>
          <div class="container answer-button">
            <p class="lead">
              <%= current_user.first_name %>, can you answer this question?
            </p>  
            <small id="answer-help-text">
              Your knowledge is deeply appreciated.
            </small> 
            <%= link_to "Answer", "#", class: "btn btn-success answer-question" %> 
            <div class="answer-form hidden">
              <div class="container answer-form-container">
                <%= render "form" %>
              </div>
            </div>
          </div>
          <hr>
        <% end %>
                      
    </div>

</div>


  <div class=question-show> 
    <div class="question-answers">
      <% if @question.answers.count > 0 %>

        <div class="container" id="answerContent">
          <div class="answers-top">
            <h4 id="answers-header">Answers</h4>
            <%= link_to "Write answer", "#", class: "btn btn-success answer-question" , id:"answer-button-inlist"%> 
          </div>
            <hr>
            <div class="answer-form hidden">
              <div class="container answer-form-container">
                <%= render "form" %>
              </div>
            </div>
            <% @question.answers.by_date.each do |answer| %>
            <div class="question-information">
              <div class="question-container">
              <div class="media">
              <%= image_tag( answer.user.avatar.url, class:"align-self-top mr-3 media-object comment", alt: answer.user.avatar.url )%>
                <div class="media-body">
                  <div class="user-reply">
                    <div class="user-reply-left">
                      <h5 class="mt-0"> <%= answer.user.user_name %> </h5>
                      <%= link_to "reply", "#", class: "btn btn-primary btn-sm btn-reply",  id: "btn-reply-#{answer.id}"%> 
                      <%= link_to ('<i class="fas fa-minus-circle delete-item"></i>').html_safe, answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' }, id:"delete-item-#{answer.id}" ,class: "hidden" %>
                    </div>
                    <% if current_user.admin == true %>
                    <span>
                        <%= link_to ('<i class="fas fa-cog"></i>').html_safe, "#", id:"edit-question-#{answer.id}", class:"edit-question" %>
                        <%= link_to 'Done', "#", id:"cancel-edit-#{answer.id}", class: "cancel-write-comment hidden", style:"margin-top:0.5rem;" %>
                    </span>
                    <% end %>
                  </div>
                  <small class="mb-0 user-info">
                    <%= answer_timestamp(answer) %>
                  </small>
                </div>
                
              </div>
                <p class="container answerText lead">
                  <%= answer.answer_text %>
                </p>

                <% answer.comments.by_date.each do |comment| %>
                  <div class="media comment-container">
                    <%= image_tag( User.find_by(id: comment.user_id).avatar.url, class:"align-self-top mr-3 media-object comment", alt: User.find_by(id: comment.user_id).avatar.url )%>
                    <div class="media-body">
                       <div class="comment-text-container">
                        <p class="lead"> <span> <%= User.find_by(id: comment.user_id).user_name %> </span> <%= comment.comment_text %> </p>
                      </div>
                      <% if current_user.admin == true %>
                          <%= link_to ('<i class="fas fa-minus-circle delete-item"></i>').html_safe, comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class:"hidden delete-comment-#{answer.id}" %>
                      <% end %>
                    </div>
                  </div>
                <% end %>

                <div class="form-container-new-comment hidden"  id="reply-container-<%= answer.id %>">
                   <%= render "formComment", answer: answer %>
                </div>
                
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>