config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :answer_ratings
  resources :questions do
    resources :answers
  end
  resources :users
  resources :topics, only: [:index, :show, :destroy]
  resources :categories, only: [:index, :show]
  resources :posts, only: [:destroy]
  resources :answers, only: [:destroy]
  resources :comments, only: [:destroy]

  post 'set_new_question_category', to: "application#set_new_question_category", as: :set_new_question_category
  post 'create_new_question', to: "application#create_new_question", as: :create_new_question
  match "home" => "home#index", as: :home_index, via: [:get, :post]
  post "create_post", to: "home#create_post", as: :create_post
  post "categories/create_topic", to: "categories#create_topic", as: :create_topic


  get 'set_topic_options', to: "application#set_topic_options", as: :set_topic_options
  match "/categories/topics/questions" => "questions#byTopic" , :via => [:get]
  post "questions/create_comment", to: "questions#create_comment",  as: :create_comment

  patch "topics/approve/:id", to: "topics#approve", as: 'approve_topics'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :questions

	validates :topic_name, presence: true
	validates :topic_name, uniqueness: true

	scope :by_id, -> { order(id: :asc) }
	scope :by_date_desc, -> { order(created_at: :desc )}

	def approve!
    update_attribute(:is_official, true)
  end

	def official?
		self.is_official
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    category_name = params[:category]
    if category_name.nil?
      @topics = Topic.all
    else
      category_id = Category.find_by(category_name: category_name)
      if category_id.nil?
        redirect_to topics_path
      else
        @topics = Topic.find_by(category_id: category_id)
      end
    end
  end

  def new
    @topic = Topic.new
  end

  def approve
    @topic = Topic.find(params[:id])
    @topic.approve!
    redirect_to user_path(@topic.user_id), notice: 'The topic has been approved'
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_path
    else
      render 'new'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end
  # show method
  # if has parameter q, filter results by query
  # else show all the current questions in topic
  def show
    @topic = Topic.find(params[:id])
    @q = @topic.questions.ransack(params[:q])
    @questions = @q.result(distinct: true)
    @is_search = false
    if params[:q].present?
        @is_search = true
    end
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      redirect_to topics_path
    else
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def topic_params
    params.require(:topic).permit(:topic_name, :is_official)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/show.html.erb
<div class="container">
    <div class="container">
        <div class="jumbotron bannerHeader" id="topicHeader">
            <h1 class="display-4"> <%= @topic.topic_name %> </h1>
            <p class="lead"> <%= @topic.description %> </p>
        </div>
    </div>
</div>

<% if @questions.count == 0 %>
            <% if @is_search %>
            <div class="container" id="topic-questions-container">
            <div class="container" id="topics">
                <%= search_form_for @q, url: topic_path do |f| %>
                    <div class="sticky-top align-flex">
                        <%= f.search_field :question_text_or_question_title_cont, class: "form-control mr-sm-2", id: "searchPost", placeholder: "Search..." %>
                        <%= f.submit class: "submit-search"%>
                    </div>
                <% end %>
            </div>
                <div class="dropdown-divider"></div>
                <div class="container no-questions-found">
                <p class="lead"> There are no results for your search </p>
            <% else %>
                <div class="dropdown-divider"> </div>
                <div class="container no-questions-found">
                <p class="lead"> There are no questions for this topic. </p>
                <small id="answer-help-text"> Your can ask anything related to this topic. </small>
                <div class="no-questions-ask-container">
                    <%= link_to "Ask something", "#new-question-modal", "data-toggle" => "modal", class: "nav-link lead", id:"link-no-question" %>
                </div>
            </div>
            <% end %>
        </div>
        <div class="dropdown-divider"></div>
    </div>
<% else %>
    <div class="container" id="topic-questions-container">
    <div class="container" id="topics">
        <%= search_form_for @q, url: topic_path do |f| %>
            <div class="sticky-top align-flex">
                <%= f.search_field :question_text_or_question_title_cont, class: "form-control mr-sm-2", id: "searchPost", placeholder: "Search..." %>
                <%= f.submit class: "submit-search"%>
            </div>
        <% end %>
    </div>
        <div class="questionContent">
            <% @questions.by_date.each do |question| %>
                <div class="question-information">
                    <div class="question-info">
                        <div class="answer-quantity"> <%= question.answers.count %> </div>
                        <div> answers </div>
                    </div>
                    <div class="question-container">
                        <div class="questionTitle">
                            <%= link_to question.question_title, question_path(question), class: "link-to-question"%>
                        </div>
                        <p class="questionText">
                            <%= question.question_text %>
                        </p>
                        <small class="user-info">
                            <%= question_show_timestamp(question) %>
                        </small>
                    </div>
                </div>
                <hr>
            <% end %>
        </div>
    </div>
<% end %>