config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :answer_ratings
  resources :questions do
    resources :answers
  end
  resources :users
  resources :topics, only: [:index, :show, :destroy]
  resources :categories, only: [:index, :show]
  resources :posts, only: [:destroy]
  resources :answers, only: [:destroy]
  resources :comments, only: [:destroy]

  post 'set_new_question_category', to: "application#set_new_question_category", as: :set_new_question_category
  post 'create_new_question', to: "application#create_new_question", as: :create_new_question
  match "home" => "home#index", as: :home_index, via: [:get, :post]
  post "create_post", to: "home#create_post", as: :create_post
  post "categories/create_topic", to: "categories#create_topic", as: :create_topic


  get 'set_topic_options', to: "application#set_topic_options", as: :set_topic_options
  match "/categories/topics/questions" => "questions#byTopic" , :via => [:get]
  post "questions/create_comment", to: "questions#create_comment",  as: :create_comment

  patch "topics/approve/:id", to: "topics#approve", as: 'approve_topics'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :topics

	validates :category_name, presence: true
	validates :category_name, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
skip_before_action :verify_authenticity_token

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @topic = Topic.new
  end

  def create_topic
    @topic = Topic.new(topic_params)
    @topic.save
    redirect_to category_path(@topic.category_id)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:category_name)
  end

  def topic_params
    params.require(:topic).permit(:topic_name, :description, :is_official, :user_id, :category_id)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:category_name)
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_suggest_topic.html.erb
<div id="new-topic-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header modal-header">
                <h5 id="new-topic-modal-title" class="modal-title lead">Suggest new topic</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <%= form_for topic, url: "create_topic" do |form| %>
            <div id="new-topic-modal-body">
                <div class="container new-topic">
                    <p class="center-horizontal">Type the name of the topic you want to suggest</p>
                    <div class="input-group mb-3 new-question-topic">
                        <%= form.text_field :topic_name, class: 'form-control lead form-center-horizontal',  data: { autocomplete_source: set_topic_options_path } %>
                    </div>
                    <p class="center-horizontal">Choose the category it corresponds to</p>
                    <div class="form-group mb-3">

                        <%= form.collection_select :category_id, Category.all, :id, :category_name, {}, {class: "form-control lead form-center-horizontal"} %>
                        <%= form.hidden_field :user_id, value: current_user.id %>
                        <%= form.hidden_field :is_official, value: false %>

                    </div>
                    <p class="center-horizontal">Write a brief description about the topic</p>
                    <div class="form-group mb-3">
                        <%= form.text_area :description, class:"form-control lead form-center-horizontal", id:"exampleFormControlTextarea1", rows:3, placeholder:"Write one or two sentences about this topic..." %>
                    </div>
                </div>
            </div>

            <div class="modal-footer new-question-topic">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <%= form.submit "Submit", class:"btn btn-primary btn-suggest"%>
            </div>
            <% end %>

        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="container">
    <div class="row bg-white">
        <div class="col-sm-5 col-category">
            <div class="container">
                <div class="jumbotron bannerHeader" id="categoryHeader">
                    <p class="lead">Explore and find topics in</p>
                    <h1 class="display-2">Categories</h1>
                    <p class="lead">
                    Each category can lead you to explore many topics that people have asked questions about.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-7 col-category">
        <%=image_tag("brand/SingleLogoBlackBorder.png", class: "logoDecoration", alt: "Askify-Logo") %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container" id="category-cards-container">
  <div class="row bg-white">
    <% @categories.each do |category| %>
      <div class="col-sm-6 col-category">
        <%= link_to category_path(category) do %>
          <div class="card card-category mb-3">
              <%= image_tag("categories/" + category.id.to_s+ ".jpeg", class: "card-img-top imgCategory", alt: "category.category_name")%>
              <div class="centered lead"><%= category.category_name %></div>
            </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
    <div class="container">
        <div class="jumbotron bannerHeader" id="categoryHeader">
            <div class="suggest-topic-container">
                <span class="lead">
                    Not finding what you're looking for?
                </span>
                <%= render "categories/suggest_topic", topic: @topic %>
                <%= link_to "Suggest new topic", "#new-topic-modal", "data-toggle" => "modal", class: "lead suggest-topic"%>
            </div>
            <h1 class="display-4"> <%= @category.category_name %>  </h1>
            <p class="lead">
                <%= @category.description %>
            </p>
        </div>
    </div>
    <% if @category.topics.where(is_official:true).count <= 0  %>
        <hr>
            <div class="container no-topics-found">
            <p class="lead">
                There are no topics for this category.
            </p>
            <small id="answer-help-text">
                Your suggestions for topics are deeply appreciated.
            </small>
            </div>
        <hr>
    <%end%>
</div>

<% if @category.topics.count > 0  %>
    <div class="container-fluid" id="topic-cards-container">
        <% @category.topics.by_id.each do |topic| %>
            <% if topic.is_official %>
                <%= link_to topic_path(topic) do %>
                <button name= "color<%= topic.id%9 %> " type="button" class="btn topic-button"><%= topic.topic_name %></button>
                <% end %>
            <%end%>
        <% end %>
    </div>
<% end %>