config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :answer_ratings
  resources :questions do
    resources :answers
  end
  resources :users
  resources :topics, only: [:index, :show, :destroy]
  resources :categories, only: [:index, :show]
  resources :posts, only: [:destroy]
  resources :answers, only: [:destroy]
  resources :comments, only: [:destroy]

  post 'set_new_question_category', to: "application#set_new_question_category", as: :set_new_question_category
  post 'create_new_question', to: "application#create_new_question", as: :create_new_question
  match "home" => "home#index", as: :home_index, via: [:get, :post]
  post "create_post", to: "home#create_post", as: :create_post
  post "categories/create_topic", to: "categories#create_topic", as: :create_topic


  get 'set_topic_options', to: "application#set_topic_options", as: :set_topic_options
  match "/categories/topics/questions" => "questions#byTopic" , :via => [:get]
  post "questions/create_comment", to: "questions#create_comment",  as: :create_comment

  patch "topics/approve/:id", to: "topics#approve", as: 'approve_topics'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top navbar-color">
    <a class="navbar-brand" href="/" >
      <%=image_tag("brand/SingleLogoWhiteBorder.png", class: "navbar-img", alt: "Askify-Logo") %>
    </a>

    <button id="navbar-toggler" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContentCollapsable" aria-controls="navbarContentCollapsable" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarContentCollapsable">

      <ul class="nav navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Ask something", "#new-question-modal", "data-toggle" => "modal", class: "nav-link lead", id:"linkQuestion"%>
        </li>
      </ul>

      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item mr-3">
          <%= link_to "Home", "/", class: "nav-link lead", id:"navbarHomeButton" %>
        </li>

        <li class="nav-item dropdown mr-3">

          <%= link_to "Categories", categories_path, :id => "navbarDropdownCategories", :class => "nav-link dropdown-toggle dropdown-non-hover", :"aria-haspopup" => "true", :"aria-expanded" => "false" %>

          <div id="dropdown-menu-categories" class="dropdown-menu dd-menu" aria-labelledby="navbarDropdownCategories">
            <% @categories.each do |category| %>
              <%= link_to category.category_name, category_path(category), class: "dropdown-item" %>
            <% end %>
        </li>

        <li class="nav-item dropdown mr-3">
          <a class="nav-link dropdown-toggle lead dropdown-hover" href="#" id="navbarDropdownOptions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.first_name %> 
            <% if current_user.admin? %>
              <span class="badge badge-secondary"><%= my_total_notifications %></span>
            <%end%>
          </a>

          <div id="dropdown-menu-options" class="dropdown-menu dd-menu" aria-labelledby="navbarDropdownOptions">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
              <%= link_to(destroy_user_session_path, method: :delete, class:"dropdown-item") do %>
              Sign out
              <% end %>
          </div>
        </li>
      </ul>
    </div>
</nav>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Askify</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag 'brand/SingleLogoBlackIcon.ico' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render "layouts/navbar" %>
    <% end %>
    
    <%= yield %>
    
    <% if user_signed_in? %>
      <%= render "questions/new", categories: @categories %>
    <% end %>

  </body>
</html>